### PR TITLE
Optionally compress with exomizer; the CI's will use it.

### PR DESCRIPTION
**Pull request by jepler**
Compressed from 23035 -> 13307 bytes (-42%) in my testing.

This is cumulative with the Actions PR (#8).

### CODE REVIEW

**Comment by mist64** [comment]
I'm not a fan of treating the D64 files the final build product. Yes, for testing in VICE, the Makefile needs to build a D64, but I'd rather just release PRG files when there is a release.

Otherwise, I'm very happy with this. :-)

**Comment by jepler** [comment]
OK, so you'd rather have .PRG as the main artifact? I'll revise it. I have to confess I don't really know how folks load software on their commodore 64s these days.

**Comment by jepler** [comment]
Why not skip the D64 with vice as well?  This works for me with vice 3.5 (GTK3 3.24.24, GLib 2.66.7):
```
x64sc +truedrive +cart -acia1 -acia1base 0xDE00 -acia1irq 1 -acia1mode 1 -myaciadev 0 -rsdev1 localhost:25232 -rsdev1baud 9600 -autostart build/ccgmsterm.prg
```
(note disabling of true drive emulation)

**Comment by jepler** [comment]
or "-autostartprgmode 1" to "inject to RAM"

**Comment by jepler** [comment]
I went with `-autostartprgmode 1`.  Updated this PR so that the artifacts zip contains prg files
Screenshot_2022-02-27_11-20-15
and a [test release](https://github.com/jepler/ccgmsterm/releases/tag/testrelease-1) also includes prg files and no d64 files
image

**Comment by mist64** [comment]
> Why not skip the D64 with vice as well? This works for me with vice 3.5 (GTK3 3.24.24, GLib 2.66.7):
> 
> ```
> x64sc +truedrive +cart -acia1 -acia1base 0xDE00 -acia1irq 1 -acia1mode 1 -myaciadev 0 -rsdev1 localhost:25232 -rsdev1baud 9600 -autostart build/ccgmsterm.prg
> ```
> 
> (note disabling of true drive emulation)

`+truedrive` doesn't seem to be supported by the latest VICE, but with this removed, I get the app running with a disk image attached. I do need the disk, because the unit tests read and write files.

**Pull request merged**
